<?php

/**
 * This is the model base class for the table "subzona".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Subzonas".
 *
 * Columns in table "subzona" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $EventoId
 * @property string $FuncionesId
 * @property string $ZonasId
 * @property string $SubzonaId
 * @property string $SubzonaAcc
 * @property integer $SubzonaNum
 * @property integer $SubzonaCanFil
 * @property integer $SubzonaFilCanLug
 * @property integer $SubzonaBanExp
 * @property string $SubzonaX1
 * @property string $SubzonaY1
 * @property integer $SubzonaX2
 * @property integer $SubzonaY2
 * @property integer $SubzonaX3
 * @property integer $SubzonaY3
 * @property integer $SubzonaX4
 * @property integer $SubzonaY4
 * @property integer $SubzonaX5
 * @property integer $SubzonaY5
 * @property string $SubzonaFor
 * @property string $SubzonaColor
 *
 */
abstract class BaseSubzonas extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'subzona';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Subzonas|Subzonases', $n);
	}

	public static function representingColumn() {
		return 'SubzonaAcc';
	}

	public function rules() {
		return array(
			array('EventoId, FuncionesId, ZonasId, SubzonaId, SubzonaAcc, SubzonaNum, SubzonaCanFil, SubzonaFilCanLug, SubzonaBanExp, SubzonaX1, SubzonaY1, SubzonaX2, SubzonaY2, SubzonaX3, SubzonaY3, SubzonaX4, SubzonaY4, SubzonaX5, SubzonaY5, SubzonaFor, SubzonaColor', 'required'),
			array('SubzonaNum, SubzonaCanFil, SubzonaFilCanLug, SubzonaBanExp, SubzonaX2, SubzonaY2, SubzonaX3, SubzonaY3, SubzonaX4, SubzonaY4, SubzonaX5, SubzonaY5', 'numerical', 'integerOnly'=>true),
			array('EventoId, FuncionesId, ZonasId, SubzonaId, SubzonaAcc, SubzonaFor', 'length', 'max'=>20),
			array('SubzonaX1', 'length', 'max'=>200),
			array('SubzonaY1', 'length', 'max'=>100),
			array('SubzonaColor', 'length', 'max'=>7),
			array('EventoId, FuncionesId, ZonasId, SubzonaId, SubzonaAcc, SubzonaNum, SubzonaCanFil, SubzonaFilCanLug, SubzonaBanExp, SubzonaX1, SubzonaY1, SubzonaX2, SubzonaY2, SubzonaX3, SubzonaY3, SubzonaX4, SubzonaY4, SubzonaX5, SubzonaY5, SubzonaFor, SubzonaColor', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'EventoId' => Yii::t('app', 'Evento'),
			'FuncionesId' => Yii::t('app', 'Funciones'),
			'ZonasId' => Yii::t('app', 'Zonas'),
			'SubzonaId' => Yii::t('app', 'Subzona'),
			'SubzonaAcc' => Yii::t('app', 'Subzona Acc'),
			'SubzonaNum' => Yii::t('app', 'Subzona Num'),
			'SubzonaCanFil' => Yii::t('app', 'Subzona Can Fil'),
			'SubzonaFilCanLug' => Yii::t('app', 'Subzona Fil Can Lug'),
			'SubzonaBanExp' => Yii::t('app', 'Subzona Ban Exp'),
			'SubzonaX1' => Yii::t('app', 'Subzona X1'),
			'SubzonaY1' => Yii::t('app', 'Subzona Y1'),
			'SubzonaX2' => Yii::t('app', 'Subzona X2'),
			'SubzonaY2' => Yii::t('app', 'Subzona Y2'),
			'SubzonaX3' => Yii::t('app', 'Subzona X3'),
			'SubzonaY3' => Yii::t('app', 'Subzona Y3'),
			'SubzonaX4' => Yii::t('app', 'Subzona X4'),
			'SubzonaY4' => Yii::t('app', 'Subzona Y4'),
			'SubzonaX5' => Yii::t('app', 'Subzona X5'),
			'SubzonaY5' => Yii::t('app', 'Subzona Y5'),
			'SubzonaFor' => Yii::t('app', 'Subzona For'),
			'SubzonaColor' => Yii::t('app', 'Subzona Color'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('EventoId', $this->EventoId, true);
		$criteria->compare('FuncionesId', $this->FuncionesId, true);
		$criteria->compare('ZonasId', $this->ZonasId, true);
		$criteria->compare('SubzonaId', $this->SubzonaId, true);
		$criteria->compare('SubzonaAcc', $this->SubzonaAcc, true);
		$criteria->compare('SubzonaNum', $this->SubzonaNum);
		$criteria->compare('SubzonaCanFil', $this->SubzonaCanFil);
		$criteria->compare('SubzonaFilCanLug', $this->SubzonaFilCanLug);
		$criteria->compare('SubzonaBanExp', $this->SubzonaBanExp);
		$criteria->compare('SubzonaX1', $this->SubzonaX1, true);
		$criteria->compare('SubzonaY1', $this->SubzonaY1, true);
		$criteria->compare('SubzonaX2', $this->SubzonaX2);
		$criteria->compare('SubzonaY2', $this->SubzonaY2);
		$criteria->compare('SubzonaX3', $this->SubzonaX3);
		$criteria->compare('SubzonaY3', $this->SubzonaY3);
		$criteria->compare('SubzonaX4', $this->SubzonaX4);
		$criteria->compare('SubzonaY4', $this->SubzonaY4);
		$criteria->compare('SubzonaX5', $this->SubzonaX5);
		$criteria->compare('SubzonaY5', $this->SubzonaY5);
		$criteria->compare('SubzonaFor', $this->SubzonaFor, true);
		$criteria->compare('SubzonaColor', $this->SubzonaColor, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}